### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by Road-block** [Sentilix/thaliz#1]
I like this addon a lot.  
One small gripe I have is that I can't outright replace my resurrection button / keybind with it because of how it treats conditions.  

What I would prefer is that when none of the Thaliz-specific logic is applicable it falls back to the default spell behavior.  

Taking the priest spell as an example, I'd prefer it that when none of the checks Thaliz does (group check, priority checks etc) it just loads the spell on the cursor like the default spell does.  

Similarly you can't use thaliz to ress when solo even if you have a target.

**Comment by Sentilix** [comment]
Thanks for the feedback.
I have now changed logic so when playing solo and casting a resurrection on a targetted corpse, a ress will be made. It is not 100% like the original resurrection button (yet); you cannot resurrect a released corpse this way. I still need to figure out how to target one after clicking the macro - if at all possible.

Update added in 1.4.1-beta1.

**Comment by Sentilix** [comment]
Thaliz 1.4.1 has been tested in a (wipetastic) Naxxramas raid, and therefore released.
I still need to investiage how to resurrect released corpses.
