### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Qcat0214** [Sentilix/thaliz#2]
hi.thaliz
It's like you said."If no Warlocks are up, one Warlock will be ressed after ressers are up"
Why is this?

**Comment by Sentilix** [comment]
It is to allow for summoning people running back in, while ressers are ressing remaining peeps.

**Comment by Sentilix** [comment]
Closing issue. If you think this behavior should be changed, let me know + give a good reason why :-)

Thanks for your comment.
