### ISSUE TITLE
Need improvement

### ISSUE THREAD

**Issue by Vitoshka** [Sentilix/thaliz#3]
Thank you for this interesting addon)

**Please add missing new interesting expressions**

_I also wanted to ask if there is an opportunity to add new expressions to the game yourself? Is it possible to implement this function?_

{ "(Ressing) Stop slacking and get up, %s!",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) How many \'Z\'s are in Vaelastrasz, %s?",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Did you just do the unsafety dance, %s?",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) I\'m keeping my eye on you, %s!",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Dammit, %s, I\'m a Paladin not a doctor.",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, I've got a bad feeling about this.",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Too soon, %s - you have died too soon!",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Cower, %s! The age of darkness is at hand!",			EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s! Death! Destruction!",						EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s appears to have 404\'d. Refreshing %s.",			EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Alright... where are we going to hide %s\'s body?",						EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, I know you\'re awfully comfortable down there, but you need to get up now.",			EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s. You\'ve got one more chance to do right, and it\'s tonight.",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s. Heroes never die... For a price!",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Let\'s give %s a round of applause for that beautiful demonstration of what not to do.",								EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, by clicking \'Accept\', you, the resurrected, hereby consign your soul to the resurrecter, i.e., me.",						EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) I sure hope this resurrection spell works %s, the last guy I tried it on wouldn\'t stop eating brains.",						EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s. This could have been your fault, or mine. It was probably mine... but I\'m going to go with your fault.",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Hey %s, while you\'re dead, check if Elvis is there.... And if he is able to take your spot!",							EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Don\'t worry %s, I saw this on House once!",								EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Giving %s a shot at another 10% durability loss, please stand by.",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s. The Life is meaningless. In death we trust.",								EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s! Pfft, slacker. Get back in your body and do your job! *pokes %s with a stick*",			EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s silently laughing at DPS who don\'t know when to ease up since 2004.",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) No more play, %s?",									EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Wake, %s. It is not yet your time.",							EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s. We\'re gonna need another Timmy?",							EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s I won\'t let you die !!! Well technically you\'re already dead.",			EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) It just so happens that %s is only MOSTLY dead. There\'s a big difference between mostly dead and all dead. Mostly dead is slightly alive.",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Giving %s another chance to noob it up.",							EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Wee-ooo! Wee-ooo! Wee-ooo! Wee-ooo... that\'s the best ambulance imperssion I can do, %s.",						EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Thank you %s for that excellent example of what not to do",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Hey %s, did you know it took Jesus three days to do this?",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) No time for sleepin\', get your ass back to work, %s!",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Stop laying around, %s, there\'s work to be done!",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Forgive me %s, your death only adds to my failure.",	        EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Your friends will abandon you, %s!",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, Bring out your dead! Oh, um, hi",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, Don\'t stand in fire, standing in fire is bad, Mmmkay",	EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Normally I\'d tbag your corpse, %s, but there are too many people watching today!",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Slay %s in the masters name!",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, Chuck Norris would have survived that!",			EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, seems you ran out of health!",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, you make the floor look dirty!",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, there\'s loot waiting for you!",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s, you are too late... I... must... OBEY!",			EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Shhh, %s... it will all be over soon.",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) %s! Cease this foolish venture at once!",				EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) Death is the only escape, %s.",					EMOTE_GROUP_DEFAULT, "" },
	{ "(Ressing) The time for practice is over, %s!",				EMOTE_GROUP_DEFAULT, "" }
}

**Comment by Sentilix** [comment]
If you dare to fiddle with the LUA code, you can add to or replace the default texts in the Thaliz_DefaultResurrectionMessages variable with your texts, and then from within the game do a "/script Thaliz_ResetResurrectionMessages()" to activate your macro's.

**Comment by Sentilix** [comment]
I have copied your suggestin into the roadmap. What I am thinking of is having a huge text field where you can copy or paste all emotes; i.e. "bulk editing" emotes in one go, but still need to re-think the details.

Thanks for the suggestion :-)
